apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cicd-demo-pipeline2
serialPipeline:
    stages:
      - targetId: dev-env1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-env1
customTarget:
  customTargetType: basic-custom-target
---
apiVersion: deploy.cloud.google.com/v1
kind: CustomTargetType
metadata:
  name: basic-custom-target
tasks:
  render:
    type: 'container'
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli@sha256:484e8266c1cfc84b283bc6d4eec1f6b61223115178cce76fb59f77b223f26e8e
    command: ['/bin/bash']
    args:
      - '-c'
      - |-
        echo "Sample manifest rendered content" > manifest.txt
        gcloud storage cp manifest.txt $CLOUD_DEPLOY_OUTPUT_GCS_PATH/manifest.txt
        echo {\"resultStatus\": \"SUCCEEDED\", \"manifestFile\": \"$CLOUD_DEPLOY_OUTPUT_GCS_PATH/manifest.txt\"} > results.json
        gcloud storage cp results.json $CLOUD_DEPLOY_OUTPUT_GCS_PATH/results.json
  deploy:
    type: 'container'
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
    command: ['/bin/bash']
    args:
      - '-c'
      - |-
        # Install the beta component required for App-Lifecycle Manager
        #gcloud components install beta --quiet

        # Create your ALM Rollout
        gcloud beta app-lifecycle-manager rollouts create cicd-helm-app-roll10 \
          --project="saas-demo-496915" \
          --release=cicd-helmapp-rls17 \
          --location=us-central1 \
          --rollout-kind=cicd-helm-app-rollkind1

        # Signal success back to Cloud Deploy
        echo {\"resultStatus\": \"SUCCEEDED\"} > results.json
        gcloud storage cp results.json $CLOUD_DEPLOY_OUTPUT_GCS_PATH/results.json
